name: Inference

on:
  workflow_dispatch:
    inputs:
      input_text:
        description: 'Text to classify (e.g. I feel really scared)'
        required: true
      hf_model_name:
        description: 'Hugging Face model repo'
        required: false
        default: 'jiitravi/emotion-distilbert'

jobs:
  infer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run inference
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          INPUT_TEXT: ${{ github.event.inputs.input_text }}
          HF_MODEL_NAME: ${{ github.event.inputs.hf_model_name }}
        run: python src/inference.py
